In [1]:
# class
# object
#reference variable
# constructor
# self variable
# instance, static, local

In [38]:
class A:
    def m1():
        pass
    def m2():
        pass

In [39]:
a = A()

In [18]:
class Student:
    college = 'MIT' #static variable
    def __init__(self, name, rno, marks): #function
        self.name = 'John' # instance variable
        self.rno = 1235
        self.marks = 750
        Student.country = 'India' # static variable
        
    def display(self):
        print(self.name,self.rno,self.marks)
        
    def getPerc(self):
        total = 1000
        return (self.marks/total)*100
    def selectCollege(self,cname):
        self.College = cname
    def getName(self):
        return self.name

In [12]:
s1 = Student('Harry',12321,350)

In [14]:
s1.display()

John 1235 750


In [15]:
s1.__dict__

{'marks': 750, 'name': 'John', 'rno': 1235}

In [16]:
s1.getPerc()

75.0

In [17]:
# Inheritance method

In [33]:
class A:
    def m1(self):
        print('master 1')
    def m2(self):
        print('master 2')

class B:
    def m1(self):
        print('master 1')
    def m2(self):
        print('master 2')
    def m3(self):
        print('master 3')
    def m4(self):
        print('master 4')
        
class C:
    def m1(self):
        print('master 1')
    def m2(self):
        print('master 2')
    def m3(self):
        print('master 3')
    def m4(self):
        print('master 4')
    def m5(self):
        print('master 5')
    def m6(self):
        print('master 6')

In [34]:
a = A()
b = B()
c = C()

In [35]:
a.m1()

master 1


In [36]:
a.m2()

master 2


In [37]:
c.m1()

master 1


In [27]:
# the error int he above program is due to lack of inheritance property

In [28]:
# with inheritance
class A:
    def m1(self):
        print('Class of A: Method 1')
    def m2(self):
        print('Class of A: Method 2')

class B(A):
    def m3(self):
        print('Class of B: Method 3')
    def m4(self):
        print('Class of B: Method 4')
        
class C(B):
    def m5(self):
        print('Class of C: Method 5')
    def m6(self):
        print('Class of C: Method 6')

In [29]:
a = A()
b = B()
c = C()

In [30]:
a.m1()

Class of A: Method 1


In [31]:
a.m2()

Class of A: Method 2


In [44]:
c.m3()

master 3


In [45]:
# multiple inheritance
# with inheritance
class A:
    def m1(self):
        print('Class of A: Method 1')
    def m2(self):
        print('Class of A: Method 2')

class B:
    def m3(self):
        print('Class of B: Method 3')
    def m4(self):
        print('Class of B: Method 4')
        
class C(A, B):
    def m5(self):
        print('Class of C: Method 5')
    def m6(self):
        print('Class of C: Method 6')

In [46]:
a = A()
b = B()
c = C()

In [47]:
c.m1()

Class of A: Method 1


In [56]:
class A2018(object):
    def __init__(self):
        print('batch of 2018')
        
class A2019(A2018):
    def __init__(self):
        print('batch of 2019')
        A2018.__init__(self)


In [53]:
A2019.mro()

[__main__.A2019, __main__.A2018, object]

In [58]:
A2018.mro()

[__main__.A2018, object]

# NUMPY 

In [59]:
!pip install numpy

You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [60]:
import numpy as np

In [61]:
d =  np.array([11,22,33,44])

In [62]:
d

array([11, 22, 33, 44])

In [63]:
type(d)

numpy.ndarray

In [64]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
type(np.arange(10))

numpy.ndarray

In [66]:
#example:
lst = range(1000)

In [68]:
%timeit [i**2 for i in lst]

316 µs ± 13.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [69]:
arr = np.arange(1000)

In [70]:
%timeit arr**2

1.1 µs ± 52.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [1]:
arr = np.arange(10)

NameError: name 'np' is not defined

In [2]:
arr

NameError: name 'arr' is not defined

In [73]:
arr.ndim

1

In [74]:
arr.shape

(10,)

In [75]:
len(arr)

10

In [76]:
arr.dtype

dtype('int64')

In [77]:
arr.itemsize

8

In [79]:
arr = np.array([[11,22,33],[44,55,66]])

In [80]:
arr

array([[11, 22, 33],
       [44, 55, 66]])

In [81]:
arr.shape

(2, 3)

In [82]:
len(arr)

2

In [83]:
arr.ndim

2

In [85]:
np.diag(arr)

array([11, 55])

In [90]:
np.ones((13,10))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [91]:
np.zeros((12,12))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [92]:
np.eye(10)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [93]:
np.eye(3,4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [94]:
np.random.random((3,3))

array([[ 0.85209958,  0.61068411,  0.95461353],
       [ 0.58966577,  0.93612336,  0.18191738],
       [ 0.06931458,  0.59005797,  0.43323442]])

In [98]:
arr2 = np.array([[12,32,43],[33,55,44]])

In [99]:
arr2.shape

(2, 3)

In [100]:
np.random.random((10,1))

array([[ 0.21780308],
       [ 0.54924101],
       [ 0.19951685],
       [ 0.90073072],
       [ 0.18628892],
       [ 0.08833777],
       [ 0.0113804 ],
       [ 0.09723916],
       [ 0.27527866],
       [ 0.09667492]])

In [101]:
arr3 = np.array([[21,32,34,45],[32,34,45,65],[4,5,6,7]])

In [102]:
arr3

array([[21, 32, 34, 45],
       [32, 34, 45, 65],
       [ 4,  5,  6,  7]])

In [112]:
arr3[2,3] = 99

In [113]:
arr3

array([[21, 32, 34, 45],
       [32, 34, 99, 65],
       [ 4,  5,  6, 99]])

In [114]:
arr3

array([[21, 32, 34, 45],
       [32, 34, 99, 65],
       [ 4,  5,  6, 99]])

In [115]:
arr3[::2]

array([[21, 32, 34, 45],
       [ 4,  5,  6, 99]])

In [116]:
arr3[1:3]

array([[32, 34, 99, 65],
       [ 4,  5,  6, 99]])

In [119]:
arr3[0:-2]

array([[21, 32, 34, 45]])

In [121]:
arr3[2][3]

99

In [122]:
arr3[2,3]

99

In [124]:
arr3[0:3]

array([[21, 32, 34, 45],
       [32, 34, 99, 65],
       [ 4,  5,  6, 99]])

In [125]:
arr3

array([[21, 32, 34, 45],
       [32, 34, 99, 65],
       [ 4,  5,  6, 99]])

In [126]:
arr3[:2,0:1]

array([[21],
       [32]])

In [128]:
arr3[:,0:2]

array([[21, 32],
       [32, 34],
       [ 4,  5]])

In [129]:
arr3[:,:]

array([[21, 32, 34, 45],
       [32, 34, 99, 65],
       [ 4,  5,  6, 99]])

In [130]:
# How to apply mathematical functions in Array

In [131]:
arr3

array([[21, 32, 34, 45],
       [32, 34, 99, 65],
       [ 4,  5,  6, 99]])

In [132]:
# elementwise operation
arr3*10

array([[210, 320, 340, 450],
       [320, 340, 990, 650],
       [ 40,  50,  60, 990]])

In [133]:
#square root of each element
np.sqrt(arr3)

array([[ 4.58257569,  5.65685425,  5.83095189,  6.70820393],
       [ 5.65685425,  5.83095189,  9.94987437,  8.06225775],
       [ 2.        ,  2.23606798,  2.44948974,  9.94987437]])

In [134]:
# round to the nearest integer
np.ceil(arr3)

array([[ 21.,  32.,  34.,  45.],
       [ 32.,  34.,  99.,  65.],
       [  4.,   5.,   6.,  99.]])

In [135]:
# checking the missing values
np.isnan(arr3)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]], dtype=bool)

In [137]:
# elementwise addition of numbers
arr3 + np.eye(3,4)

array([[ 22.,  32.,  34.,  45.],
       [ 32.,  35.,  99.,  65.],
       [  4.,   5.,   7.,  99.]])

In [138]:
np.eye(3,4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [139]:
arr3

array([[21, 32, 34, 45],
       [32, 34, 99, 65],
       [ 4,  5,  6, 99]])

In [140]:
np.maximum(arr3,np.eye(3,4))

array([[ 21.,  32.,  34.,  45.],
       [ 32.,  34.,  99.,  65.],
       [  4.,   5.,   6.,  99.]])

In [141]:
np.minimum(arr3,np.eye(3,4))

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [142]:
np.eye(10)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [144]:
arr3.mean()

39.666666666666664

In [145]:
arr3.std()

31.422744770132493

In [146]:
arr3.argmin() #index of the minimum value

8

In [147]:
arr3.argmax() #index of the maximum value

6

In [148]:
arr3

array([[21, 32, 34, 45],
       [32, 34, 99, 65],
       [ 4,  5,  6, 99]])

In [149]:
arr3.sum()

476

In [150]:
# conditional logic

In [151]:
np.where(arr3 > 10,999,222)

array([[999, 999, 999, 999],
       [999, 999, 999, 999],
       [222, 222, 222, 999]])

In [152]:
np.where(arr3 > 40,777,arr3)

array([[ 21,  32,  34, 777],
       [ 32,  34, 777, 777],
       [  4,   5,   6, 777]])

In [153]:
arr3.min()

4

In [154]:
arr3.max()

99

In [157]:
arr3[0:,:1].max()

32

In [161]:
arr3[0:1,0:1]

array([[21]])

In [162]:
arr3[0:1,0:]

array([[21, 32, 34, 45]])

In [163]:
arr3[0:,0:1]

array([[21],
       [32],
       [ 4]])

In [165]:
arr3[:-1,:-1]

array([[21, 32, 34],
       [32, 34, 99]])

In [166]:
arr3

array([[21, 32, 34, 45],
       [32, 34, 99, 65],
       [ 4,  5,  6, 99]])

In [172]:
(arr3 > 50).sum()

3

In [173]:
(arr3 < 10).any()

True

In [174]:
(arr3 < 10).all()

False

In [175]:
# reshape, transpose or flatten

In [176]:
arr3

array([[21, 32, 34, 45],
       [32, 34, 99, 65],
       [ 4,  5,  6, 99]])

In [177]:
nums = np.arange(32)

In [178]:
nums

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [179]:
# create an array of size 8X4

In [180]:
nums.reshape(8,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [181]:
nums.reshape(4,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [182]:
arr4 =nums.reshape(8,4)

In [183]:
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [184]:
arr4.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [189]:
arr5 = arr4.flatten()

In [190]:
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [191]:
arr5.reshape(4,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [192]:
arr4.reshape(1,32)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [200]:
# random number generation
np.random.seed(5555)

In [201]:
np.random.seed(444)
np.random.rand(2,3) #gives values between 0-1

array([[ 0.83936105,  0.82129497,  0.64220716],
       [ 0.66722262,  0.03913991,  0.06567239]])

In [203]:
np.random.seed(444)
np.random.rand(2,3) #gives values between 0-1

array([[ 0.83936105,  0.82129497,  0.64220716],
       [ 0.66722262,  0.03913991,  0.06567239]])

In [204]:
# random number generation between mean 0, sd 1
np.random.randn(10)

array([-0.9392757 , -1.14315015, -0.54243951, -0.54870808,  0.20851975,
        0.21268956,  1.26802054, -0.80730293, -3.30307164, -0.80664959])

In [212]:
# random num gene in a range
np.random.randint(100,150,300)

array([140, 114, 124, 144, 102, 119, 129, 103, 127, 110, 146, 124, 110,
       145, 111, 122, 130, 118, 118, 119, 120, 128, 128, 110, 112, 106,
       110, 124, 141, 112, 127, 146, 125, 121, 126, 109, 111, 140, 113,
       102, 137, 130, 121, 111, 134, 131, 119, 136, 101, 147, 121, 115,
       126, 111, 132, 134, 130, 104, 138, 147, 145, 112, 102, 106, 124,
       144, 134, 128, 133, 146, 128, 113, 103, 129, 105, 133, 149, 136,
       145, 101, 137, 128, 110, 137, 124, 104, 102, 126, 133, 144, 120,
       135, 111, 114, 133, 103, 104, 110, 149, 126, 119, 131, 129, 120,
       149, 149, 108, 101, 137, 131, 142, 126, 136, 128, 128, 134, 123,
       116, 127, 122, 107, 115, 100, 118, 146, 102, 100, 139, 143, 141,
       118, 122, 112, 127, 144, 119, 124, 119, 101, 118, 134, 148, 115,
       128, 141, 118, 123, 104, 141, 141, 123, 106, 122, 108, 130, 148,
       108, 145, 133, 141, 113, 120, 145, 106, 118, 131, 143, 110, 112,
       128, 117, 146, 121, 112, 144, 139, 149, 121, 138, 130, 13

In [213]:
mat1 = np.random.randint(100,150,9).reshape(3,3)

In [214]:
mat1

array([[126, 147, 141],
       [141, 121, 126],
       [108, 106, 113]])

In [215]:
mat2 = np.random.randint(100,150,9).reshape(3,3)

In [216]:
mat2

array([[117, 108, 142],
       [121, 121, 141],
       [109, 121, 115]])

In [217]:
mat1 + mat2

array([[243, 255, 283],
       [262, 242, 267],
       [217, 227, 228]])

In [218]:
mat1 * mat2

array([[14742, 15876, 20022],
       [17061, 14641, 17766],
       [11772, 12826, 12995]])

In [219]:
mat1/mat2

array([[ 1.07692308,  1.36111111,  0.99295775],
       [ 1.16528926,  1.        ,  0.89361702],
       [ 0.99082569,  0.87603306,  0.9826087 ]])

In [220]:
#3*A - 2*B

3*mat1 - 2*mat2

array([[144, 225, 139],
       [181, 121,  96],
       [106,  76, 109]])

In [221]:
100+mat1

array([[226, 247, 241],
       [241, 221, 226],
       [208, 206, 213]])

In [222]:
mat1**3

array([[2000376, 3176523, 2803221],
       [2803221, 1771561, 2000376],
       [1259712, 1191016, 1442897]])

In [223]:
pow(mat1,0.5)

array([[ 11.22497216,  12.12435565,  11.87434209],
       [ 11.87434209,  11.        ,  11.22497216],
       [ 10.39230485,  10.29563014,  10.63014581]])

In [224]:
np.sqrt(mat1)

array([[ 11.22497216,  12.12435565,  11.87434209],
       [ 11.87434209,  11.        ,  11.22497216],
       [ 10.39230485,  10.29563014,  10.63014581]])

In [225]:
# broadcasting in numpy arrays

In [226]:
mat3 = np.zeros((4,3))

In [227]:
mat3

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [228]:
# create a rank 1 ndarray with 3 values

In [233]:
new_row = np.array([1,10,2])

In [234]:
new_row

array([ 1, 10,  2])

In [235]:
# add to each row of the mat3 using the broadcasting rule
mat3 + new_row

array([[  1.,  10.,   2.],
       [  1.,  10.,   2.],
       [  1.,  10.,   2.],
       [  1.,  10.,   2.]])

In [236]:
# create an ndarray 4x1 to broadcast across different columns

In [237]:
new_col = np.array([[0,1,2,3]])

In [238]:
new_col


array([[0, 1, 2, 3]])

In [240]:
mat3 + new_col.T

array([[ 0.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

In [241]:
one_value = np.array([225])

In [242]:
mat3 + one_value

array([[ 225.,  225.,  225.],
       [ 225.,  225.,  225.],
       [ 225.,  225.,  225.],
       [ 225.,  225.,  225.]])

In [243]:
mat3 + 225

array([[ 225.,  225.,  225.],
       [ 225.,  225.,  225.],
       [ 225.,  225.,  225.],
       [ 225.,  225.,  225.]])

In [245]:
A = np.array([[2,5,1],[3,-2,-1],[1,-3,1]])
B = np.array([14,-1,4])

In [246]:
A

array([[ 2,  5,  1],
       [ 3, -2, -1],
       [ 1, -3,  1]])

In [247]:
B

array([14, -1,  4])

In [248]:
np.linalg.solve(A,B)

array([ 2.,  1.,  5.])

In [249]:
# x = 2, y = 1, z = 5

In [250]:
np.linalg.inv(A) #inverse of a matrix

array([[ 0.13513514,  0.21621622,  0.08108108],
       [ 0.10810811, -0.02702703, -0.13513514],
       [ 0.18918919, -0.2972973 ,  0.51351351]])

In [251]:
np.linalg.pinv(A) #Pseudo Inverse of a matrix

array([[ 0.13513514,  0.21621622,  0.08108108],
       [ 0.10810811, -0.02702703, -0.13513514],
       [ 0.18918919, -0.2972973 ,  0.51351351]])

In [256]:
np.round(np.dot(np.linalg.inv(A),A),3) #matri multiplication

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [255]:
# trace of a matrix

In [257]:
A

array([[ 2,  5,  1],
       [ 3, -2, -1],
       [ 1, -3,  1]])

In [258]:
np.trace(A)

1

In [259]:
mat1

array([[126, 147, 141],
       [141, 121, 126],
       [108, 106, 113]])

In [260]:
np.trace(mat1)

360

In [263]:
np.trace(mat2)
mat2

array([[117, 108, 142],
       [121, 121, 141],
       [109, 121, 115]])

In [264]:
np.trace(mat3)
mat3

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [265]:
mat2

array([[117, 108, 142],
       [121, 121, 141],
       [109, 121, 115]])

In [267]:
mat1

array([[126, 147, 141],
       [141, 121, 126],
       [108, 106, 113]])

In [268]:
np.matmul(mat1,mat2)

array([[47898, 48456, 54834],
       [44872, 45115, 51573],
       [37779, 38163, 43277]])

In [269]:
np.dot(mat1,mat2)

array([[47898, 48456, 54834],
       [44872, 45115, 51573],
       [37779, 38163, 43277]])