`!pip install numpy` # This way we can install using Jupyter Notebook

In [1]:
import numpy as np   # Array
import pandas as pd  # DataFrame

In [2]:
# numpy array 3 columns and 2 rows
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# numpy matrix. Matrix can't be multi dimensional.
np.matrix([[1,2,3],[4,5,6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [4]:
# bool_
np.array([[1,2,-1],[0,5,6]], 'bool_')

array([[ True,  True,  True],
       [False,  True,  True]])

In [5]:
# int_
np.matrix([[1,2,3],[4,5,6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [6]:
# int8
np.matrix([[1,2,3],[4,5,6]], 'b')

matrix([[1, 2, 3],
        [4, 5, 6]], dtype=int8)

In [7]:
# int16
np.matrix([[1,2,3],[4,5,6]], 'h')

matrix([[1, 2, 3],
        [4, 5, 6]], dtype=int16)

In [8]:
# int32
np.matrix([[1,2,3],[4,5,6]], 'i')

matrix([[1, 2, 3],
        [4, 5, 6]], dtype=int32)

In [9]:
# int64
np.matrix([[1,2,3],[4,5,6]], 'l')

matrix([[1, 2, 3],
        [4, 5, 6]])

In [10]:
# float_
np.matrix([[1,2,3],[4,5,6]], 'float_')

matrix([[1., 2., 3.],
        [4., 5., 6.]])

In [11]:
np.matrix([[1,2,3],[4.,5,6]])

matrix([[1., 2., 3.],
        [4., 5., 6.]])

In [12]:
# float16
np.matrix([[1,2,3],[4.,5,6]], 'e')

matrix([[1., 2., 3.],
        [4., 5., 6.]], dtype=float16)

In [13]:
# float32
np.matrix([[1,2,3],[4.,5,6]], 'f')

matrix([[1., 2., 3.],
        [4., 5., 6.]], dtype=float32)

In [14]:
# float64
np.matrix([[1,2,3],[4.,5,6]], 'd')

matrix([[1., 2., 3.],
        [4., 5., 6.]])

In [15]:
# float128
np.matrix([[1,2,3],[4.,5,6]], 'g')

matrix([[1., 2., 3.],
        [4., 5., 6.]], dtype=float128)

In [16]:
# complex_
np.matrix([[1,2,3],[4.,5,6]], 'complex_')

matrix([[1.+0.j, 2.+0.j, 3.+0.j],
        [4.+0.j, 5.+0.j, 6.+0.j]])

In [17]:
# Text
np.array([
    ['i', 'am', 'a', 'data', 'geek'],
    ['looking', 'forward', 'to', 'learn', 'machine', 'learning']
])
np.nbytes

{numpy.bool_: 1,
 numpy.int8: 1,
 numpy.uint8: 1,
 numpy.int16: 2,
 numpy.uint16: 2,
 numpy.int32: 4,
 numpy.uint32: 4,
 numpy.int64: 8,
 numpy.uint64: 8,
 numpy.int64: 8,
 numpy.uint64: 8,
 numpy.float16: 2,
 numpy.float32: 4,
 numpy.float64: 8,
 numpy.float128: 16,
 numpy.complex64: 8,
 numpy.complex128: 16,
 numpy.complex256: 32,
 numpy.object_: 8,
 numpy.bytes_: 0,
 numpy.str_: 0,
 numpy.void: 0,
 numpy.datetime64: 8,
 numpy.timedelta64: 8}

In [18]:
np.NaN

nan

In [19]:
# Panda Series
df = pd.Series([[1,2,3],[4.,5,6]])
df

0      [1, 2, 3]
1    [4.0, 5, 6]
dtype: object

In [20]:
df.shape

(2,)

In [21]:
# Panda Series - one dimensional
pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
dtype: int64

In [22]:
df = pd.DataFrame([
    [1,2,3],
    ['i', 'am', 'a'],
    [1., 2., 3.],
    [1.+0.j, 2.+0.j, 3.+0.j],
    [1.+0.j, 2.+0.j, 3.+0.j],
    [1.+0.j, 2.+0.j, 3.+0.j],
    [1.+0.j, 2.+0.j, 3.+0.j],
    [1.+0.j, 2.+0.j, 3.+0.j],
    [1.+0.j, 2.+0.j, 3.+0.j],
    [1.+0.j, 2.+0.j, 3.+0.j],
    [1.+0.j, 2.+0.j, 3.+0.j],
    [1.+0.j, 2.+0.j, 3.+0.j],
    [1.+0.j, 2.+0.j, 3.+0.j],
    [1.+0.j, 2.+0.j, 3.+0.j],
    [1.+0.j, 2.+0.j, 3.+0.j],
    [1.+0.j, 2.+0.j]
])
df

0       1       2
0        1       2       3
1        i      am       a
2        1       2       3
3   (1+0j)  (2+0j)  (3+0j)
4   (1+0j)  (2+0j)  (3+0j)
5   (1+0j)  (2+0j)  (3+0j)
6   (1+0j)  (2+0j)  (3+0j)
7   (1+0j)  (2+0j)  (3+0j)
8   (1+0j)  (2+0j)  (3+0j)
9   (1+0j)  (2+0j)  (3+0j)
10  (1+0j)  (2+0j)  (3+0j)
11  (1+0j)  (2+0j)  (3+0j)
12  (1+0j)  (2+0j)  (3+0j)
13  (1+0j)  (2+0j)  (3+0j)
14  (1+0j)  (2+0j)  (3+0j)
15  (1+0j)  (2+0j)    None

In [23]:
df.values

array([[1, 2, 3],
       ['i', 'am', 'a'],
       [1.0, 2.0, 3.0],
       [(1+0j), (2+0j), (3+0j)],
       [(1+0j), (2+0j), (3+0j)],
       [(1+0j), (2+0j), (3+0j)],
       [(1+0j), (2+0j), (3+0j)],
       [(1+0j), (2+0j), (3+0j)],
       [(1+0j), (2+0j), (3+0j)],
       [(1+0j), (2+0j), (3+0j)],
       [(1+0j), (2+0j), (3+0j)],
       [(1+0j), (2+0j), (3+0j)],
       [(1+0j), (2+0j), (3+0j)],
       [(1+0j), (2+0j), (3+0j)],
       [(1+0j), (2+0j), (3+0j)],
       [(1+0j), (2+0j), None]], dtype=object)

In [24]:
df.head()

0       1       2
0       1       2       3
1       i      am       a
2       1       2       3
3  (1+0j)  (2+0j)  (3+0j)
4  (1+0j)  (2+0j)  (3+0j)

In [25]:
df.shape

(16, 3)

In [26]:
df = pd.read_csv(
    'http://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data',
    header=None,
    sep=','
)
df

0      1     2     3     4    5     6     7     8     9          10  \
0     1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.640000   
1     1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.380000   
2     1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.680000   
3     1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.800000   
4     1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.320000   
5     1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97   6.750000   
6     1  14.39  1.87  2.45  14.6   96  2.50  2.52  0.30  1.98   5.250000   
7     1  14.06  2.15  2.61  17.6  121  2.60  2.51  0.31  1.25   5.050000   
8     1  14.83  1.64  2.17  14.0   97  2.80  2.98  0.29  1.98   5.200000   
9     1  13.86  1.35  2.27  16.0   98  2.98  3.15  0.22  1.85   7.220000   
10    1  14.10  2.16  2.30  18.0  105  2.95  3.32  0.22  2.38   5.750000   
11    1  14.12  1.48  2.32  16.8   95  2.20  2.43  0.26  1.57   5.000000   
12    1  13.75  1.73  2.41  16.0   89  2.60  2.76  0.29  1.81   5.600000   
13    1  14.75  1.73  2.39  11.4   91  3.10  3.69  0.43  2.81   5.400000   
14    1  14.38  1.87  2.38  12.0  102  3.30  3.64  0.29  2.96   7.500000   
15    1  13.63  1.81  2.70  17.2  112  2.85  2.91  0.30  1.46   7.300000   
16    1  14.30  1.92  2.72  20.0  120  2.80  3.14  0.33  1.97   6.200000   
17    1  13.83  1.57  2.62  20.0  115  2.95  3.40  0.40  1.72   6.600000   
18    1  14.19  1.59  2.48  16.5  108  3.30  3.93  0.32  1.86   8.700000   
19    1  13.64  3.10  2.56  15.2  116  2.70  3.03  0.17  1.66   5.100000   
20    1  14.06  1.63  2.28  16.0  126  3.00  3.17  0.24  2.10   5.650000   
21    1  12.93  3.80  2.65  18.6  102  2.41  2.41  0.25  1.98   4.500000   
22    1  13.71  1.86  2.36  16.6  101  2.61  2.88  0.27  1.69   3.800000   
23    1  12.85  1.60  2.52  17.8   95  2.48  2.37  0.26  1.46   3.930000   
24    1  13.50  1.81  2.61  20.0   96  2.53  2.61  0.28  1.66   3.520000   
25    1  13.05  2.05  3.22  25.0  124  2.63  2.68  0.47  1.92   3.580000   
26    1  13.39  1.77  2.62  16.1   93  2.85  2.94  0.34  1.45   4.800000   
27    1  13.30  1.72  2.14  17.0   94  2.40  2.19  0.27  1.35   3.950000   
28    1  13.87  1.90  2.80  19.4  107  2.95  2.97  0.37  1.76   4.500000   
29    1  14.02  1.68  2.21  16.0   96  2.65  2.33  0.26  1.98   4.700000   
..   ..    ...   ...   ...   ...  ...   ...   ...   ...   ...        ...   
148   3  13.32  3.24  2.38  21.5   92  1.93  0.76  0.45  1.25   8.420000   
149   3  13.08  3.90  2.36  21.5  113  1.41  1.39  0.34  1.14   9.400000   
150   3  13.50  3.12  2.62  24.0  123  1.40  1.57  0.22  1.25   8.600000   
151   3  12.79  2.67  2.48  22.0  112  1.48  1.36  0.24  1.26  10.800000   
152   3  13.11  1.90  2.75  25.5  116  2.20  1.28  0.26  1.56   7.100000   
153   3  13.23  3.30  2.28  18.5   98  1.80  0.83  0.61  1.87  10.520000   
154   3  12.58  1.29  2.10  20.0  103  1.48  0.58  0.53  1.40   7.600000   
155   3  13.17  5.19  2.32  22.0   93  1.74  0.63  0.61  1.55   7.900000   
156   3  13.84  4.12  2.38  19.5   89  1.80  0.83  0.48  1.56   9.010000   
157   3  12.45  3.03  2.64  27.0   97  1.90  0.58  0.63  1.14   7.500000   
158   3  14.34  1.68  2.70  25.0   98  2.80  1.31  0.53  2.70  13.000000   
159   3  13.48  1.67  2.64  22.5   89  2.60  1.10  0.52  2.29  11.750000   
160   3  12.36  3.83  2.38  21.0   88  2.30  0.92  0.50  1.04   7.650000   
161   3  13.69  3.26  2.54  20.0  107  1.83  0.56  0.50  0.80   5.880000   
162   3  12.85  3.27  2.58  22.0  106  1.65  0.60  0.60  0.96   5.580000   
163   3  12.96  3.45  2.35  18.5  106  1.39  0.70  0.40  0.94   5.280000   
164   3  13.78  2.76  2.30  22.0   90  1.35  0.68  0.41  1.03   9.580000   
165   3  13.73  4.36  2.26  22.5   88  1.28  0.47  0.52  1.15   6.620000   
166   3  13.45  3.70  2.60  23.0  111  1.70  0.92  0.43  1.46  10.680000   
167   3  12.82  3.37  2.30  19.5   88  1.48  0.66  0.40  0.97  10.260000   
168   3  13.58  2.58  2.69  24.5  105  1.55  0.84  0.

In [27]:
# panel
df = pd.Panel([[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]])
df

/Users/vpendyala/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2963: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


<class 'pandas.core.panel.Panel'>
Dimensions: 1 (items) x 1 (major_axis) x 10 (minor_axis)
Items axis: 0 to 0
Major_axis axis: 0 to 0
Minor_axis axis: 0 to 9

In [28]:
# panel4D Looks like deprecated/depreciate 
df = pd.Panel([[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]],dtype=str)
df.axes

/Users/vpendyala/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2963: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


[RangeIndex(start=0, stop=1, step=1),
 RangeIndex(start=0, stop=1, step=1),
 RangeIndex(start=0, stop=10, step=1)]

In [29]:
x = complex(2, 3)
x

(2+3j)

In [30]:
x.real, x.imag 

(2.0, 3.0)

In [31]:
d = np.array([11, 12, 13])

In [32]:
d

array([11, 12, 13])

In [33]:
type(d)

numpy.ndarray

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
type(np.arange(10))

numpy.ndarray

In [36]:
#Speed Test
lst = range(1000)

In [37]:
%timeit [i**2 for i in lst]

280 µs ± 10.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [38]:
arr = np.arange(1000)

In [39]:
%timeit arr**2

1.14 µs ± 41.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [40]:
arr.ndim # Find the dimension of the array

1

In [41]:
arr.shape # Find the shape of the array

(1000,)

In [42]:
len(arr)

1000

In [43]:
arr.dtype

dtype('int64')

In [44]:
arr.itemsize # Memory size of each item it is 8 bits

8

In [45]:
arr = np.array([[11,22,33], [11, 12,13]])

In [46]:
arr.ndim

2

In [47]:
arr.shape # 2 rows and 3 columns

(2, 3)

In [48]:
len(arr)

2

In [49]:
np.diag(arr)

array([11, 12])

In [50]:
arr.itemsize # data type 

8

In [51]:
np.ones([13, 10]) # Ones matrix

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [52]:
np.zeros([13, 10]) # zeros matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [53]:
np.eye(10) # 1 dimensional array

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [54]:
np.eye(3,4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [55]:
# Random matrix
np.random.random([3,4])

array([[0.35987685, 0.20996201, 0.26998545, 0.03777125],
       [0.41594812, 0.997411  , 0.41058616, 0.41707577],
       [0.66527399, 0.25457971, 0.19032639, 0.18664783]])

In [56]:
np.random.randint(10)

5

In [57]:
arr2 = np.array([[12, 13], [11, 22, 33]])
arr2.shape

(2,)

In [58]:
arr3 = np.array([[12, 13, 14], [11, 22, 33]])
arr3.shape

(2, 3)

In [59]:
np.random.random([10, 1])

array([[0.68145088],
       [0.33221742],
       [0.89010684],
       [0.69688827],
       [0.99251076],
       [0.90764137],
       [0.45841399],
       [0.17713214],
       [0.60497534],
       [0.98951874]])

In [60]:
arr4 = np.array([[1,2,3,4], [11,22,33,44], [11, 12, 13, 14]])

In [61]:
arr4

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44],
       [11, 12, 13, 14]])

In [62]:
arr4.shape

(3, 4)

In [63]:
arr4[0] # first row

array([1, 2, 3, 4])

In [64]:
arr4[1] # second row

array([11, 22, 33, 44])

In [65]:
arr4[2] # third row

array([11, 12, 13, 14])

In [66]:
arr4[:2] # Extract rows

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [67]:
arr4[2:3] # Extract starting 2 to 3 rows

array([[11, 12, 13, 14]])

In [68]:
arr4[2,3]

14

In [69]:
arr4[2,3] = 99

In [70]:
arr4

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44],
       [11, 12, 13, 99]])

In [71]:
arr4[:,0]

array([ 1, 11, 11])

In [72]:
arr4[::2]

array([[ 1,  2,  3,  4],
       [11, 12, 13, 99]])

In [73]:
arr4[1:3]

array([[11, 22, 33, 44],
       [11, 12, 13, 99]])

In [74]:
arr4[0:-2]

array([[1, 2, 3, 4]])

In [75]:
arr4[2][3]

99

In [76]:
arr4[2,3]

99

In [77]:
arr4[0:3]

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44],
       [11, 12, 13, 99]])

In [78]:
arr4[:2,0:1]

array([[ 1],
       [11]])

In [79]:
arr4[:3,0:2]

array([[ 1,  2],
       [11, 22],
       [11, 12]])

In [80]:
arr4[:,:]

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44],
       [11, 12, 13, 99]])

# How to apply mathematical functions in Array

In [81]:
arr = np.array([[1,2,3,4], [11,22,33,44], [11, 12, 13, 14]])

In [82]:
arr

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44],
       [11, 12, 13, 14]])

In [83]:
# elementwise operation broadcasting
arr * 10

array([[ 10,  20,  30,  40],
       [110, 220, 330, 440],
       [110, 120, 130, 140]])

In [84]:
#square root on each element
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [3.31662479, 4.69041576, 5.74456265, 6.63324958],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [85]:
# round to the nearest integer
np.ceil(arr)

array([[ 1.,  2.,  3.,  4.],
       [11., 22., 33., 44.],
       [11., 12., 13., 14.]])

In [86]:
# Checking the missing values 
# nan - Not a number
np.isnan(arr)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [87]:
# elemente wise addition of numbers, addition broadcasting
arr + 1000

array([[1001, 1002, 1003, 1004],
       [1011, 1022, 1033, 1044],
       [1011, 1012, 1013, 1014]])

In [88]:
arr + np.eye(3, 4)

array([[ 2.,  2.,  3.,  4.],
       [11., 23., 33., 44.],
       [11., 12., 14., 14.]])

In [89]:
np.maximum(arr, np.eye(3,4))

array([[ 1.,  2.,  3.,  4.],
       [11., 22., 33., 44.],
       [11., 12., 13., 14.]])

In [90]:
np.minimum(arr, np.eye(3,4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [91]:
np.max(arr)

44

In [92]:
np.min(arr)

1

In [93]:
arr.mean() # Mean on array

14.166666666666666

In [94]:
arr.std() # Standard Deveation on array

12.522202504174558

In [95]:
arr.argmin() #index of the minimum value

0

In [96]:
arr.argmax() #index of the maximum value

7

In [97]:
arr.size # No of elements in array

12

In [98]:
arr.sum() # Sum of all the element in the array

170

# Conditional logic

In [100]:
np.where(arr > 10,999,222) # if element greater than 10 we change the value to 999 
# if the condition not satisfied we convert to 222

array([[222, 222, 222, 222],
       [999, 999, 999, 999],
       [999, 999, 999, 999]])

In [104]:
np.where(arr > 13,999,arr) # if element is greater than 13 we change to 999
# Else retain the arr

array([[  1,   2,   3,   4],
       [ 11, 999, 999, 999],
       [ 11,  12,  13, 999]])

In [105]:
arr.min()

1

In [106]:
arr.max()

44

In [108]:
arr[0:, :1].max()

11

In [109]:
arr[0:1,0:1]

array([[1]])

In [111]:
arr[0:1,0:] # First value from all the columns

array([[1, 2, 3, 4]])

In [112]:
arr[0:,0:1] # First value from all the rows

array([[ 1],
       [11],
       [11]])

In [114]:
arr[:-1,:-1]

array([[ 1,  2,  3],
       [11, 22, 33]])

In [115]:
arr[-1:,-1:]

array([[14]])

In [116]:
arr

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44],
       [11, 12, 13, 14]])

In [118]:
(arr > 14).sum()

3

In [120]:
(arr >= 14)

array([[False, False, False, False],
       [False,  True,  True,  True],
       [False, False, False,  True]])

In [121]:
(arr > 100).any() # Any value

False

In [122]:
(arr > 10).any() # Any value 

True

In [123]:
(arr < 10).all() # Some not less than 10

False

In [125]:
(arr < 500).all() # All the values are less than 500

True

# reshape, transpose and flatten

In [127]:
arr

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44],
       [11, 12, 13, 14]])